The Nobel Prize has been among the most prestigious international awards since 1901. Each year, awards are bestowed in chemistry, literature, physics, physiology or medicine, economics, and peace. In addition to the honor, prestige, and substantial prize money, the recipient also gets a gold medal with an image of Alfred Nobel (1833 - 1896), who established the prize.

![](Nobel_Prize.png)

The Nobel Foundation has made a dataset available of all prize winners from the outset of the awards from 1901 to 2023. The dataset used in this project is from the Nobel Prize API and is available in the `nobel.csv` file in the `data` folder.

In this project, you'll get a chance to explore and answer several questions related to this prizewinning data. And we encourage you then to explore further questions that you're interested in!

In [ ]:
# Loading in required libraries
import pandas as pd
import seaborn as sns
import numpy as np

# Start coding here!

# Load the dataset and find the most common gender and birth country

In [4]:
nobel_prize_winner_df = pd.read_csv('data/nobel.csv')
nobel_prize_winner_df

,year,category,prize,motivation,prize_share,laureate_id,laureate_type,full_name,birth_date,birth_city,birth_country,sex,organization_name,organization_city,organization_country,death_date,death_city,death_country
0,1901,Chemistry,The Nobel Prize in Chemistry 1901,"""in recognition of the extraordinary services ...",1/1,160,Individual,Jacobus Henricus van 't Hoff,1852-08-30,Rotterdam,Netherlands,Male,Berlin University,Berlin,Germany,1911-03-01,Berlin,Germany
1,1901,Literature,The Nobel Prize in Literature 1901,"""in special recognition of his poetic composit...",1/1,569,Individual,Sully Prudhomme,1839-03-16,Paris,France,Male,NaN,NaN,NaN,1907-09-07,Châtenay,France
2,1901,Medicine,The Nobel Prize in Physiology or Medicine 1901,"""for his work on serum therapy, especially its...",1/1,293,Individual,Emil Adolf von Behring,1854-03-15,Hansdorf (Lawice),Prussia (Poland),Male,Marburg University,Marburg,Germany,1917-03-31,Marburg,Germany
3,1901,Peace,The Nobel Peace Prize 1901,NaN,1/2,462,Individual,Jean Henry Dunant,1828-05-08,Geneva,Switzerland,Male,NaN,NaN,NaN,1910-10-30,Heiden,Switzerland
4,1901,Peace,The Nobel Peace Prize 1901,NaN,1/2,463,Individual,Frédéric Passy,1822-05-20,Paris,France,Male,NaN,NaN,NaN,1912-06-12,Paris,France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,Chemistry,The Nobel Prize in Chemistry 2023,"""for the discovery and synthesis of quantum dots""",1/3,1030,Individual,Louis Brus,1943-00-00,"Cleveland, OH",United States of America,Male,Columbia University,"New York, NY",United States of America,NaN,NaN,NaN
996,2023,Chemistry,The Nobel Prize in Chemistry 2023,"""for the discovery and synthesis of quantum dots""",1/3,1031,Individual,Aleksey Yekimov,1945-00-00,NaN,USSR (now Russia),Male,Nanocrystals Technology Inc.,"New York, NY",United States of America,NaN,NaN,NaN
997,2023,Literature,The Nobel Prize in Literature 2023,"""for his innovative plays and prose which give...",1/1,1032,Individual,Jon Fosse,1959-09-29,Haugesund,Norway,Male,NaN,NaN,NaN,NaN,NaN,NaN
998,2023,Peace,The Nobel Peace Prize 2023,"""for her fight against the oppression of women...",1/1,1033,Individual,Narges Mohammadi,1972-04-21,Zanjan,Iran,Female,NaN,NaN,NaN,NaN,NaN,NaN
999,2023,Economics,The Sveriges Riksbank Prize in Economic Scienc...,"""for having advanced our understanding of wome...",1/1,1034,Individual,Claudia Goldin,1946-00-00,"New York, NY",United States of America,Female,Harvard University,"Cambridge, MA",United States of America,NaN,NaN,NaN

## Get the top_gender

In [7]:
nobel_prize_winner_df['sex'].value_counts().index[0]
# Get the most common gender and store it into the variable 'top_gender' 
top_gender = nobel_prize_winner_df['sex'].value_counts().index[0]
print(top_gender)

Male

## Get the top_country

In [14]:
nobel_prize_winner_df['birth_country'].value_counts()
nobel_prize_winner_df['birth_country'].value_counts().index[0]
top_country = nobel_prize_winner_df['birth_country'].value_counts().index[0]
print(top_country)

United States of America

# Identify the decade with the highest ratio of US-born winners
Which decade had the highest ratio of US-born Nobel Prize winners to total winners in all categories
    Store this as an integer called 'max_decade_usa'

## Create the US-born winners column

In [17]:
nobel_prize_winner_df['usa_born_winner'] = nobel_prize_winner_df['birth_country'] == 'United States of America'
nobel_prize_winner_df

,year,category,prize,motivation,prize_share,laureate_id,laureate_type,full_name,birth_date,birth_city,birth_country,sex,organization_name,organization_city,organization_country,death_date,death_city,death_country,usa_born_winner
0,1901,Chemistry,The Nobel Prize in Chemistry 1901,"""in recognition of the extraordinary services ...",1/1,160,Individual,Jacobus Henricus van 't Hoff,1852-08-30,Rotterdam,Netherlands,Male,Berlin University,Berlin,Germany,1911-03-01,Berlin,Germany,False
1,1901,Literature,The Nobel Prize in Literature 1901,"""in special recognition of his poetic composit...",1/1,569,Individual,Sully Prudhomme,1839-03-16,Paris,France,Male,NaN,NaN,NaN,1907-09-07,Châtenay,France,False
2,1901,Medicine,The Nobel Prize in Physiology or Medicine 1901,"""for his work on serum therapy, especially its...",1/1,293,Individual,Emil Adolf von Behring,1854-03-15,Hansdorf (Lawice),Prussia (Poland),Male,Marburg University,Marburg,Germany,1917-03-31,Marburg,Germany,False
3,1901,Peace,The Nobel Peace Prize 1901,NaN,1/2,462,Individual,Jean Henry Dunant,1828-05-08,Geneva,Switzerland,Male,NaN,NaN,NaN,1910-10-30,Heiden,Switzerland,False
4,1901,Peace,The Nobel Peace Prize 1901,NaN,1/2,463,Individual,Frédéric Passy,1822-05-20,Paris,France,Male,NaN,NaN,NaN,1912-06-12,Paris,France,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,Chemistry,The Nobel Prize in Chemistry 2023,"""for the discovery and synthesis of quantum dots""",1/3,1030,Individual,Louis Brus,1943-00-00,"Cleveland, OH",United States of America,Male,Columbia University,"New York, NY",United States of America,NaN,NaN,NaN,True
996,2023,Chemistry,The Nobel Prize in Chemistry 2023,"""for the discovery and synthesis of quantum dots""",1/3,1031,Individual,Aleksey Yekimov,1945-00-00,NaN,USSR (now Russia),Male,Nanocrystals Technology Inc.,"New York, NY",United States of America,NaN,NaN,NaN,False
997,2023,Literature,The Nobel Prize in Literature 2023,"""for his innovative plays and prose which give...",1/1,1032,Individual,Jon Fosse,1959-09-29,Haugesund,Norway,Male,NaN,NaN,NaN,NaN,NaN,NaN,False
998,2023,Peace,The Nobel Peace Prize 2023,"""for her fight against the oppression of women...",1/1,1033,Individual,Narges Mohammadi,1972-04-21,Zanjan,Iran,Female,NaN,NaN,NaN,NaN,NaN,NaN,False
999,2023,Economics,The Sveriges Riksbank Prize in Economic Scienc...,"""for having advanced our understanding of wome...",1/1,1034,Individual,Claudia Goldin,1946-00-00,"New York, NY",United States of America,Female,Harvard University,"Cambridge, MA",United States of America,NaN,NaN,NaN,True

In [19]:
nobel_prize_winner_df[nobel_prize_winner_df['usa_born_winner']==True]

,year,category,prize,motivation,prize_share,laureate_id,laureate_type,full_name,birth_date,birth_city,birth_country,sex,organization_name,organization_city,organization_country,death_date,death_city,death_country,usa_born_winner
35,1906,Peace,The Nobel Peace Prize 1906,NaN,1/1,470,Individual,Theodore Roosevelt,1858-10-27,"New York, NY",United States of America,Male,NaN,NaN,NaN,1919-01-06,"Oyster Bay, NY",United States of America,True
72,1912,Peace,The Nobel Peace Prize 1912,NaN,1/1,480,Individual,Elihu Root,1845-02-15,"Clinton, NY",United States of America,Male,NaN,NaN,NaN,1937-02-07,"New York, NY",United States of America,True
79,1914,Chemistry,The Nobel Prize in Chemistry 1914,"""in recognition of his accurate determinations...",1/1,175,Individual,Theodore William Richards,1868-01-31,"Germantown, PA",United States of America,Male,Harvard University,"Cambridge, MA",United States of America,1928-04-02,"Cambridge, MA",United States of America,True
95,1919,Peace,The Nobel Peace Prize 1919,NaN,1/1,483,Individual,Thomas Woodrow Wilson,1856-12-28,"Staunton, VA",United States of America,Male,NaN,NaN,NaN,1924-02-03,"Washington, DC",United States of America,True
117,1923,Physics,The Nobel Prize in Physics 1923,"""for his work on the elementary charge of elec...",1/1,28,Individual,Robert Andrews Millikan,1868-03-22,"Morrison, IL",United States of America,Male,California Institute of Technology (Caltech),"Pasadena, CA",United States of America,1953-12-19,"San Marino, CA",United States of America,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,2022,Economics,The Sveriges Riksbank Prize in Economic Scienc...,"""for research on banks and financial crises""",1/3,1022,Individual,Douglas Diamond,1953-10-25,"Chicago, IL",United States of America,Male,University of Chicago,"Chicago, IL",United States of America,NaN,NaN,NaN,True
988,2022,Economics,The Sveriges Riksbank Prize in Economic Scienc...,"""for research on banks and financial crises""",1/3,1023,Individual,Philip Dybvig,1955-05-22,"Gainesville, FL",United States of America,Male,Washington University,"St. Louis, MO",United States of America,NaN,NaN,NaN,True
990,2023,Medicine,The Nobel Prize in Physiology or Medicine 2023,"""for their discoveries concerning nucleoside b...",1/2,1025,Individual,Drew Weissman,1959-09-07,"Lexington, MA",United States of America,Male,Penn Institute for RNA Innovations University ...,"Philadelphia, PA",United States of America,NaN,NaN,NaN,True
995,2023,Chemistry,The Nobel Prize in Chemistry 2023,"""for the discovery and synthesis of quantum dots""",1/3,1030,Individual,Louis Brus,1943-00-00,"Cleveland, OH",United States of America,Male,Columbia University,"New York, NY",United States of America,NaN,NaN,NaN,True
999,2023,Economics,The Sveriges Riksbank Prize in Economic Scienc...,"""for having advanced our understanding of wome...",1/1,1034,Individual,Claudia Goldin,1946-00-00,"New York, NY",United States of America,Female,Harvard University,"Cambridge, MA",United States of America,NaN,NaN,NaN,True

## Create the decade column

In [25]:
nobel_prize_winner_df['year'].unique()

array([1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911,
       1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922,
       1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933,
       1934, 1935, 1936, 1937, 1938, 1939, 1943, 1944, 1945, 1946, 1947,
       1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958,
       1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969,
       1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980,
       1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023])

In [27]:
# Convert the year column into a decade column 
# Use integer division by 10 and then multiple by 10
nobel_prize_winner_df['decade'] = (nobel_prize_winner_df['year']//10 ) * 10
nobel_prize_winner_df

,year,category,prize,motivation,prize_share,laureate_id,laureate_type,full_name,birth_date,birth_city,birth_country,sex,organization_name,organization_city,organization_country,death_date,death_city,death_country,usa_born_winner,decade
0,1901,Chemistry,The Nobel Prize in Chemistry 1901,"""in recognition of the extraordinary services ...",1/1,160,Individual,Jacobus Henricus van 't Hoff,1852-08-30,Rotterdam,Netherlands,Male,Berlin University,Berlin,Germany,1911-03-01,Berlin,Germany,False,1900
1,1901,Literature,The Nobel Prize in Literature 1901,"""in special recognition of his poetic composit...",1/1,569,Individual,Sully Prudhomme,1839-03-16,Paris,France,Male,NaN,NaN,NaN,1907-09-07,Châtenay,France,False,1900
2,1901,Medicine,The Nobel Prize in Physiology or Medicine 1901,"""for his work on serum therapy, especially its...",1/1,293,Individual,Emil Adolf von Behring,1854-03-15,Hansdorf (Lawice),Prussia (Poland),Male,Marburg University,Marburg,Germany,1917-03-31,Marburg,Germany,False,1900
3,1901,Peace,The Nobel Peace Prize 1901,NaN,1/2,462,Individual,Jean Henry Dunant,1828-05-08,Geneva,Switzerland,Male,NaN,NaN,NaN,1910-10-30,Heiden,Switzerland,False,1900
4,1901,Peace,The Nobel Peace Prize 1901,NaN,1/2,463,Individual,Frédéric Passy,1822-05-20,Paris,France,Male,NaN,NaN,NaN,1912-06-12,Paris,France,False,1900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,Chemistry,The Nobel Prize in Chemistry 2023,"""for the discovery and synthesis of quantum dots""",1/3,1030,Individual,Louis Brus,1943-00-00,"Cleveland, OH",United States of America,Male,Columbia University,"New York, NY",United States of America,NaN,NaN,NaN,True,2020
996,2023,Chemistry,The Nobel Prize in Chemistry 2023,"""for the discovery and synthesis of quantum dots""",1/3,1031,Individual,Aleksey Yekimov,1945-00-00,NaN,USSR (now Russia),Male,Nanocrystals Technology Inc.,"New York, NY",United States of America,NaN,NaN,NaN,False,2020
997,2023,Literature,The Nobel Prize in Literature 2023,"""for his innovative plays and prose which give...",1/1,1032,Individual,Jon Fosse,1959-09-29,Haugesund,Norway,Male,NaN,NaN,NaN,NaN,NaN,NaN,False,2020
998,2023,Peace,The Nobel Peace Prize 2023,"""for her fight against the oppression of women...",1/1,1033,Individual,Narges Mohammadi,1972-04-21,Zanjan,Iran,Female,NaN,NaN,NaN,NaN,NaN,NaN,False,2020
999,2023,Economics,The Sveriges Riksbank Prize in Economic Scienc...,"""for having advanced our understanding of wome...",1/1,1034,Individual,Claudia Goldin,1946-00-00,"New York, NY",United States of America,Female,Harvard University,"Cambridge, MA",United States of America,NaN,NaN,NaN,True,2020

In [30]:
nobel_prize_winner_df['decade'].unique()
nobel_prize_winner_df[nobel_prize_winner_df['decade'] == 1910]

,year,category,prize,motivation,prize_share,laureate_id,laureate_type,full_name,birth_date,birth_city,birth_country,sex,organization_name,organization_city,organization_country,death_date,death_city,death_country,usa_born_winner,decade
57,1910,Chemistry,The Nobel Prize in Chemistry 1910,"""in recognition of his services to organic che...",1/1,169,Individual,Otto Wallach,1847-03-27,Koenigsberg (Kaliningrad),Germany (Russia),Male,Goettingen University,Göttingen,Germany,1931-02-26,Göttingen,Germany,False,1910
58,1910,Literature,The Nobel Prize in Literature 1910,"""as a tribute to the consummate artistry, perm...",1/1,580,Individual,Paul Johann Ludwig Heyse,1830-03-15,Berlin,Prussia (Germany),Male,NaN,NaN,NaN,1914-04-02,Munich,Germany,False,1910
59,1910,Medicine,The Nobel Prize in Physiology or Medicine 1910,"""in recognition of the contributions to our kn...",1/1,304,Individual,Albrecht Kossel,1853-09-16,Rostock,Mecklenburg (Germany),Male,University of Heidelberg,Heidelberg,Germany,1927-07-05,Heidelberg,Germany,False,1910
60,1910,Peace,The Nobel Peace Prize 1910,NaN,1/1,477,Organization,Bureau international permanent de la Paix (Per...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,1910
61,1910,Physics,The Nobel Prize in Physics 1910,"""for his work on the equation of state for gas...",1/1,15,Individual,Johannes Diderik van der Waals,1837-11-23,Leiden,Netherlands,Male,Amsterdam University,Amsterdam,Netherlands,1923-03-08,Amsterdam,Netherlands,False,1910
62,1911,Chemistry,The Nobel Prize in Chemistry 1911,"""in recognition of her services to the advance...",1/1,6,Individual,"Marie Curie, née Sklodowska",1867-11-07,Warsaw,Russian Empire (Poland),Female,Sorbonne University,Paris,France,1934-07-04,Sallanches,France,False,1910
63,1911,Literature,The Nobel Prize in Literature 1911,"""in appreciation of his many-sided literary ac...",1/1,581,Individual,Count Maurice (Mooris) Polidore Marie Bernhard...,1862-08-29,Ghent,Belgium,Male,NaN,NaN,NaN,1949-05-06,Nice,France,False,1910
64,1911,Medicine,The Nobel Prize in Physiology or Medicine 1911,"""for his work on the dioptrics of the eye""",1/1,305,Individual,Allvar Gullstrand,1862-06-05,Landskrona,Sweden,Male,Uppsala University,Uppsala,Sweden,1930-07-28,Stockholm,Sweden,False,1910
65,1911,Peace,The Nobel Peace Prize 1911,NaN,1/2,478,Individual,Tobias Michael Carel Asser,1838-04-28,Amsterdam,Netherlands,Male,NaN,NaN,NaN,1913-07-29,the Hague,Netherlands,False,1910
66,1911,Peace,The Nobel Peace Prize 1911,NaN,1/2,479,Individual,Alfred Hermann Fried,1864-11-11,Vienna,Austria,Male,NaN,NaN,NaN,1921-05-05,Vienna,Austria,False,1910
67,1911,Physics,The Nobel Prize in Physics 1911,"""for his discoveries regarding the laws govern...",1/1,16,Individual,Wilhelm Wien,1864-01-13,Gaffken (Parusnoye),Prussia (Russia),Male,Würzburg University,Würzburg,Germany,1928-08-30,Munich,Germany,False,1910
68,1912,Chemistry,The Nobel Prize in Chemistry 1912,"""for the discovery of the so-called Grignard r...",1/2,172,Individual,Victor Grignard,1871-05-06,Cherbourg,France,Male,Nancy University,Nancy,France,1935-12-13,Lyon,France,False,1910
69,1912,Chemistry,The Nobel Prize in Chemistry 1912,"""for his method of hydrogenating organic compo...",1/2,173,Individual,Paul Sabatier,1854-11-05,Carcassonne,France,Male,Toulouse University,Toulouse,France,1941-08-14,Toulouse,France,False,1910
70,1912,Literature,The Nobel Prize in Literature 1912,"""primarily in recognition of his fruitful, var...",1/1,582,Individual,Gerhart Johann Robert Hauptmann,1862-11-15,Bad Salzbrunn,Prussia (Germany),Male,NaN,NaN,NaN,1946-06-06,Agnetendorf (Jagniatków),Germany (Poland),False,1910
71,1912,Medicine,The Nobel Prize in Physiology or Medicine 1912,"""in recognition of his work on vascular suture...",1/1,306,Individual,Alexis Carrel,1873-06-28,Sainte-Foy-lès-Lyon,France,Male,Rockefeller Institute for Medical Research,"New York, NY",United States of America,1944-11-05,Paris,France,False,1910
72,1912,Peace,The Nobel Peace Prize 1912,NaN,1/1,480,Individual,Elihu Root,1845-02-15,"Clinton, NY",United States of America,Male,NaN,NaN,NaN,1937-02-07,"New York, NY",United States of America,True,1910
73,1912,Physics,The Nobel Prize in Physics 1912,"""for his invention of automatic regulators for...",1/1,17,Individual,Nils Gustaf Dalén,1869-11-30,Stenstorp,Sweden,Male,Swedish Gas-Accumulator Co.,Lidingö-Stockholm,Sweden,1937-12-09,Stockholm,Sweden,False,1910
74,1913,Chemistry,The Nobel Prize in Chemistry 1913,"""in recognition of his work on the linkage of ...",1/1,174,Individual,Alfred Werner,1866-12-12,Mulhouse,France,Male,University of Zurich,Zurich,Switzerland,1919-11-15,Zurich,Switzerland,False,1910
75,1913,Literature,The Nobel Prize in Literature 1913,"""because of his profoundly sensitive, fresh an...",1/1,583,Individual,Rabindranath Tagore,1861-05-07,Calcutta,India,Male,NaN,NaN,NaN,1941-08-07,Calcutta,India,False,1910
76,1913,Medicine,The Nobel Prize in Physiology or Medicine 1913,"""in recognition of his work on anaphylaxis""",1/1,307,Individual,Charles Robert Richet,1850-08-26,Paris,France,Male,Sorbonne University,Paris,France,1935-12-04,Paris,France,False,1910
77,1913,Peace,The Nobel Peace Prize 1913,NaN,1/1,481,Individual,Henri La Fontaine,1854-04-22,Brussels,Belgium,Male,NaN,NaN,NaN,1943-05-14,Brussels,Belgium,False,1910
78,1913,Physics,The Nobel Prize in Physics 1913,"""for his investigations on the properties of m...",1/1,18,Individual,Heike Kamerlingh Onnes,1853-09-21,Groningen,Netherlands,Male,Leiden University,Leiden,Netherlands,1926-02-21,Leiden,Netherlands,False,1910
79,1914,Chemistry,The Nobel Prize in Chemistry 1914,"""in recognition of his accurate determinations...",1/1,175,Individual,Theodore William Richards,1868-01-31,"Germantown, PA",United States of America,Male,Harvard University,"Cambridge, MA",United States of America,1928-04-02,"Cambridge, MA",United States of America,True,1910
80,1914,Medicine,The Nobel Prize in Physiology or Medicine 1914,"""for his work on the physiology and pathology ...",1/1,308,Individual,Robert Bárány,1876-04-22,Vienna,Austria,Male,Vienna University,Vienna,Austria,1936-04-08,Uppsala,Sweden,False,1910
81,1914,Physics,The Nobel Prize in Physics 1914,"""for his discovery of the diffraction of X-ray...",1/1,19,Individual,Max von Laue,1879-10-09,Pfaffendorf,Germany,Male,Frankfurt-on-the-Main University,Frankfurt-on-the-Main,Germany,1960-04-23,Berlin,West Germany (Germany),False,1910
82,1915,Chemistry,The Nobel Prize in Chemistry 1915,"""for his researches on plant pigments, especia...",1/1,176,Individual,Richard Martin Willstätter,1872-08-13,Karlsruhe,Germany,Male,Munich University,Munich,Germany,1942-08-03,Locarno,Switzerland,False,1910
83,1915,Literature,The Nobel Prize in Literature 1915,"""as a tribute to the lofty idealism of his lit...",1/1,584,Individual,Romain Rolland,1866-01-29,Clamecy,France,Male,NaN,NaN,NaN,1944-12-30,Vézelay,France,False,1910
84,1915,Physics,The Nobel Prize in Physics 1915,"""for their services in the analysis of crystal...",1/2,20,Individual,Sir William Henry Bragg,1862-07-02,Wigton,United Kingdom,Male,University College,London,United Kingdom,1942-03-12,London,United Kingdom,False,1910
85,1915,Physics,The Nobel Prize in Physics 1915,"""for their services in the analysis of crystal...",1/2,21,Individual,William Lawrence Bragg,1890-03-31,Adelaide,Australia,Male,Victoria University,Manchester,United Kingdom,1971-07-01,Ipswich,United Kingdom,False,1910
86,1916,Literature,The Nobel Prize in Literature 1916,"""in recognition of his significance as the lea...",1/1,585,Individual,Carl Gustaf Verner von Heidenstam,1859-07-06,Olshammar,Sweden,Male,NaN,NaN,NaN,1940-05-20,Övralid,Sweden,False,1910
87,1917,Literature,The Nobel Prize in Literature 1917,"""for his varied and rich poetry, which is insp...",1/2,586,Individual,Karl Adolph Gjellerup,1857-06-02,Roholte,Denmark,Male,NaN,NaN,NaN,1919-10-11,Klotzsche,Germany,False,1910
88,1917,Literature,The Nobel Prize in Literature 1917,"""for his authentic descriptions of present-day...",1/2,587,Individual,Henrik Pontoppidan,1857-07-24,Fredericia,Denmark,Male,NaN,NaN,NaN,1943-08-21,Ordrup,Denmark,False,1910
89,1917,Peace,The Nobel Peace Prize 1917,NaN,1/1,482,Organization,Comité international de la Croix Rouge (Intern...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,1910
90,1917,Physics,The Nobel Prize in Physics 1917,"""for his discovery of the characteristic R&oum...",1/1,22,Individual,Charles Glover Barkla,1877-06-07,Widnes,United Kingdom,Male,Edinburgh University,Edinburgh,United Kingdom,1944-10-23,Edinburgh,Scotland,False,1910
91,1918,Chemistry,The Nobel Prize in Chemistry 1918,"""for the synthesis of ammonia from its elements""",1/1,177,Individual,Fritz Haber,1868-12-09,Breslau (Wroclaw),Prussia (Poland),Male,Kaiser-Wilhelm-Institut (now Fritz-Haber-Insti...,Berlin-Dahlem,Germany,1934-01-29,Basel,Switzerland,False,1910
92,1918,Physics,The Nobel Prize in Physics 1918,"""in recognition of the services he rendered to...",1/1,23,Individual,Max Karl Ernst Ludwig Planck,1858-04-23,Kiel,Schleswig (Germany),Male,Berlin University,Berlin,Germany,1947-10-04,Göttingen,West Germany (Germany),False,1910
93,1919,Literature,The Nobel Prize in Literature 1919,"""in special appreciation of his epic, <I>Olymp...",1/1,588,Individual,Carl Friedrich Georg Spitteler,1845-04-24,Liestal,Switzerland,Male,NaN,NaN,NaN,1924-12-29,Lucerne,Switzerland,False,1910
94,1919,Medicine,The Nobel Prize in Physiology or Medicine 1919,"""for his discoveries relating to immunity""",1/1,309,Individual,Jules Bordet,1870-06-13,Soignies,Belgium,Male,Brussels University,Brussels,Belgium,1961-04-06,Brussels,Belgium,False,1910
95,1919,Peace,The Nobel Peace Prize 1919,NaN,1/1,483,Individual,Thomas Woodrow Wilson,1856-12-28,"Staunton, VA",United States of America,Male,NaN,NaN,NaN,1924-02-03,"Washington, DC",United States of America,True,1910
96,1919,Physics,The Nobel Prize in Physics 1919,"""for his discovery of the Doppler effect in ca...",1/1,24,Individual,Johannes Stark,1874-04-15,Schickenhof,Germany,Male,Greifswald University,Greifswald,Germany,1957-06-21,Traunstein,West Germany (Germany),False,1910

## Finding the ratio

In [32]:
prop_usa_winners =nobel_prize_winner_df.groupby('decade',as_index=False)['usa_born_winner'].mean()

In [33]:
prop_usa_winners

    decade  usa_born_winner
0     1900         0.017544
1     1910         0.075000
2     1920         0.074074
3     1930         0.250000
4     1940         0.302326
5     1950         0.291667
6     1960         0.265823
7     1970         0.317308
8     1980         0.319588
9     1990         0.403846
10    2000         0.422764
11    2010         0.314050
12    2020         0.360000

## Identify the decade with the highest ratio of US-born winners

In [47]:
max_decade_usa = prop_usa_winners[prop_usa_winners['usa_born_winner'] == prop_usa_winners['usa_born_winner'].max()]['decade'].values[0]
print(max_decade_usa)

2000

# Find the decade and category with the highest proportion of female laurates

In [48]:
nobel_prize_winner_df

,year,category,prize,motivation,prize_share,laureate_id,laureate_type,full_name,birth_date,birth_city,birth_country,sex,organization_name,organization_city,organization_country,death_date,death_city,death_country,usa_born_winner,decade
0,1901,Chemistry,The Nobel Prize in Chemistry 1901,"""in recognition of the extraordinary services ...",1/1,160,Individual,Jacobus Henricus van 't Hoff,1852-08-30,Rotterdam,Netherlands,Male,Berlin University,Berlin,Germany,1911-03-01,Berlin,Germany,False,1900
1,1901,Literature,The Nobel Prize in Literature 1901,"""in special recognition of his poetic composit...",1/1,569,Individual,Sully Prudhomme,1839-03-16,Paris,France,Male,NaN,NaN,NaN,1907-09-07,Châtenay,France,False,1900
2,1901,Medicine,The Nobel Prize in Physiology or Medicine 1901,"""for his work on serum therapy, especially its...",1/1,293,Individual,Emil Adolf von Behring,1854-03-15,Hansdorf (Lawice),Prussia (Poland),Male,Marburg University,Marburg,Germany,1917-03-31,Marburg,Germany,False,1900
3,1901,Peace,The Nobel Peace Prize 1901,NaN,1/2,462,Individual,Jean Henry Dunant,1828-05-08,Geneva,Switzerland,Male,NaN,NaN,NaN,1910-10-30,Heiden,Switzerland,False,1900
4,1901,Peace,The Nobel Peace Prize 1901,NaN,1/2,463,Individual,Frédéric Passy,1822-05-20,Paris,France,Male,NaN,NaN,NaN,1912-06-12,Paris,France,False,1900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,Chemistry,The Nobel Prize in Chemistry 2023,"""for the discovery and synthesis of quantum dots""",1/3,1030,Individual,Louis Brus,1943-00-00,"Cleveland, OH",United States of America,Male,Columbia University,"New York, NY",United States of America,NaN,NaN,NaN,True,2020
996,2023,Chemistry,The Nobel Prize in Chemistry 2023,"""for the discovery and synthesis of quantum dots""",1/3,1031,Individual,Aleksey Yekimov,1945-00-00,NaN,USSR (now Russia),Male,Nanocrystals Technology Inc.,"New York, NY",United States of America,NaN,NaN,NaN,False,2020
997,2023,Literature,The Nobel Prize in Literature 2023,"""for his innovative plays and prose which give...",1/1,1032,Individual,Jon Fosse,1959-09-29,Haugesund,Norway,Male,NaN,NaN,NaN,NaN,NaN,NaN,False,2020
998,2023,Peace,The Nobel Peace Prize 2023,"""for her fight against the oppression of women...",1/1,1033,Individual,Narges Mohammadi,1972-04-21,Zanjan,Iran,Female,NaN,NaN,NaN,NaN,NaN,NaN,False,2020
999,2023,Economics,The Sveriges Riksbank Prize in Economic Scienc...,"""for having advanced our understanding of wome...",1/1,1034,Individual,Claudia Goldin,1946-00-00,"New York, NY",United States of America,Female,Harvard University,"Cambridge, MA",United States of America,NaN,NaN,NaN,True,2020

## Filtering for female winners

In [51]:
nobel_prize_winner_df['female_winners'] = nobel_prize_winner_df['sex'] == 'Female'

In [53]:
nobel_prize_winner_df[nobel_prize_winner_df['female_winners'] == True]

,year,category,prize,motivation,prize_share,laureate_id,laureate_type,full_name,birth_date,birth_city,...,sex,organization_name,organization_city,organization_country,death_date,death_city,death_country,usa_born_winner,decade,female_winners
19,1903,Physics,The Nobel Prize in Physics 1903,"""in recognition of the extraordinary services ...",1/4,6,Individual,"Marie Curie, née Sklodowska",1867-11-07,Warsaw,...,Female,NaN,NaN,NaN,1934-07-04,Sallanches,France,False,1900,True
29,1905,Peace,The Nobel Peace Prize 1905,NaN,1/1,468,Individual,"Baroness Bertha Sophie Felicita von Suttner, n...",1843-06-09,Prague,...,Female,NaN,NaN,NaN,1914-06-21,Vienna,Austria,False,1900,True
51,1909,Literature,The Nobel Prize in Literature 1909,"""in appreciation of the lofty idealism, vivid ...",1/1,579,Individual,Selma Ottilia Lovisa Lagerlöf,1858-11-20,Mårbacka,...,Female,NaN,NaN,NaN,1940-03-16,Mårbacka,Sweden,False,1900,True
62,1911,Chemistry,The Nobel Prize in Chemistry 1911,"""in recognition of her services to the advance...",1/1,6,Individual,"Marie Curie, née Sklodowska",1867-11-07,Warsaw,...,Female,Sorbonne University,Paris,France,1934-07-04,Sallanches,France,False,1910,True
128,1926,Literature,The Nobel Prize in Literature 1926,"""for her idealistically inspired writings whic...",1/1,597,Individual,Grazia Deledda,1871-09-27,"Nuoro, Sardinia",...,Female,NaN,NaN,NaN,1936-08-15,Rome,Italy,False,1920,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,2022,Literature,The Nobel Prize in Literature 2022,"""for the courage and clinical acuity with whic...",1/1,1017,Individual,Annie Ernaux,1940-09-01,Lillebonne,...,Female,NaN,NaN,NaN,NaN,NaN,NaN,False,2020,True
989,2023,Medicine,The Nobel Prize in Physiology or Medicine 2023,"""for their discoveries concerning nucleoside b...",1/2,1024,Individual,Katalin Karikó,1955-01-17,Szolnok,...,Female,Szeged University,Szeged,Hungary,NaN,NaN,NaN,False,2020,True
993,2023,Physics,The Nobel Prize in Physics 2023,"""for experimental methods that generate attose...",1/3,1028,Individual,Anne L’Huillier,1958-08-16,Paris,...,Female,Lund University,Lund,Sweden,NaN,NaN,NaN,False,2020,True
998,2023,Peace,The Nobel Peace Prize 2023,"""for her fight against the oppression of women...",1/1,1033,Individual,Narges Mohammadi,1972-04-21,Zanjan,...,Female,NaN,NaN,NaN,NaN,NaN,NaN,False,2020,True
999,2023,Economics,The Sveriges Riksbank Prize in Economic Scienc...,"""for having advanced our understanding of wome...",1/1,1034,Individual,Claudia Goldin,1946-00-00,"New York, NY",...,Female,Harvard University,"Cambridge, MA",United States of America,NaN,NaN,NaN,True,2020,True

## Group by two columns

In [61]:
female_winners =nobel_prize_winner_df.groupby(['decade','category'], as_index =False)['female_winners'].mean()
female_winners

    decade    category  female_winners
0     1900   Chemistry        0.000000
1     1900  Literature        0.100000
2     1900    Medicine        0.000000
3     1900       Peace        0.071429
4     1900     Physics        0.076923
..     ...         ...             ...
67    2020   Economics        0.111111
68    2020  Literature        0.500000
69    2020    Medicine        0.125000
70    2020       Peace        0.285714
71    2020     Physics        0.166667

[72 rows x 3 columns]

In [70]:
female_winners.sort_values(by='female_winners',ascending=False).head(1)

    decade    category  female_winners
68    2020  Literature             0.5

In [ ]:
max_female_decade_category = female_winners[female_winners['female_winners'] == female_winners['female_winners'].max()][['decade', 'category']]
max_female_decade_category

    decade    category
68    2020  Literature

## Create a dictionary

In [75]:
max_female_dict = {max_female_decade_category['decade'].values[0]: max_female_decade_category['category'].values[0]}

In [76]:
print(max_female_dict)

{np.int64(2020): 'Literature'}

# Find first woman to win a Nobel Prize

In [89]:
female_winners_df =nobel_prize_winner_df[nobel_prize_winner_df['female_winners']]
first_female_winner_column = female_winners_df[female_winners_df['year']== female_winners_df['year'].min()]
first_female_winner_column

,year,category,prize,motivation,prize_share,laureate_id,laureate_type,full_name,birth_date,birth_city,...,sex,organization_name,organization_city,organization_country,death_date,death_city,death_country,usa_born_winner,decade,female_winners
19,1903,Physics,The Nobel Prize in Physics 1903,"""in recognition of the extraordinary services ...",1/4,6,Individual,"Marie Curie, née Sklodowska",1867-11-07,Warsaw,...,Female,NaN,NaN,NaN,1934-07-04,Sallanches,France,False,1900,True

In [94]:
first_women_name = first_female_winner_column['full_name'].values[0]
first_women_category =first_female_winner_column['category'].values[0]
print(first_women_name)
print(first_women_category)

Marie Curie, née Sklodowska
Physics

# Determine repeat winners

In [ ]:
counts =nobel_prize_winner_df['full_name'].value_counts()
counts

full_name
Comité international de la Croix Rouge (International Committee of the Red Cross)    3
Frederick Sanger                                                                     2
Marie Curie, née Sklodowska                                                          2
Office of the United Nations High Commissioner for Refugees (UNHCR)                  2
John Bardeen                                                                         2
                                                                                    ..
Louis Brus                                                                           1
Aleksey Yekimov                                                                      1
Jon Fosse                                                                            1
Narges Mohammadi                                                                     1
William Randal Cremer                                                                1
Name: count, Length: 993, dtype: int64

In [101]:
repeats = counts [counts > 2].index
repeats
repeat_list = list(repeats)
repeat_list

['Comité international de la Croix Rouge (International Committee of the Red Cross)']